import canonical from './canonical-sample.json';

type Sample = {
  job_id: string;
  generated_at: string;
  goal: string;
  target_url: string;
  final_url: string;
  is_highlight?: boolean;
  highlight_caption?: string;
};

async function fetchLiveSamples(): Promise<Sample[]> {
  const base = process.env.HELPER_BASE_URL ?? 'https://studio.sshub.dev';
  try {
    const r = await fetch(`${base}/helper/samples`, { next: { revalidate: 60 } });
    if (!r.ok) return [];
    return (await r.json()) as Sample[];
  } catch {
    return [];
  }
}

export default async function SampleGrid() {
  const live = await fetchLiveSamples();
  const featured = canonical as Sample;
  const additional = live.filter((s) => s.job_id !== featured.job_id);

  return (
    <div className="my-12 space-y-12">
      <figure className="group relative">
        <div
          aria-hidden="true"
          className="pointer-events-none absolute -inset-1 -z-10 rounded-xl bg-gradient-to-br from-amber-400/15 via-transparent to-amber-700/10 opacity-70 blur"
        />
        <div className="overflow-hidden rounded-xl border border-neutral-800 bg-black shadow-2xl shadow-black/60 ring-1 ring-amber-400/5">
          <div className="flex items-center gap-2 border-b border-neutral-800 bg-neutral-950 px-4 py-2.5 font-mono text-[0.65rem] uppercase tracking-[0.22em] text-neutral-500">
            <span className="size-1.5 rounded-full bg-amber-400 shadow-[0_0_8px_rgba(251,191,36,0.7)]" />
            <span>Featured · generated by the helper</span>
            <span className="ml-auto truncate text-neutral-600">
              {featured.target_url.replace(/^https?:\/\//, '')}
            </span>
          </div>
          <video
            controls
            preload="metadata"
            className="aspect-video w-full bg-black"
          >
            <source src={featured.final_url} type="video/mp4" />
          </video>
        </div>
        <figcaption className="mt-5 max-w-prose">
          <div className="font-mono text-[0.65rem] uppercase tracking-[0.22em] text-amber-400/80">
            {featured.goal}
          </div>
          {featured.highlight_caption && (
            <p className="font-display mt-3 text-xl italic leading-snug text-neutral-300">
              &ldquo;{featured.highlight_caption}&rdquo;
            </p>
          )}
        </figcaption>
      </figure>

      {additional.length > 0 && (
        <div>
          <div className="mb-4 font-mono text-[0.65rem] uppercase tracking-[0.22em] text-neutral-500">
            Additional samples ({additional.length})
          </div>
          <div className="grid gap-5 md:grid-cols-2">
            {additional.map((s) => (
              <figure
                key={s.job_id}
                className="overflow-hidden rounded-md border border-neutral-800 bg-neutral-950/60 transition-colors hover:border-neutral-700"
              >
                <video
                  controls
                  preload="metadata"
                  className="aspect-video w-full bg-black"
                >
                  <source src={s.final_url} type="video/mp4" />
                </video>
                <figcaption className="p-4 text-sm">
                  <div className="text-neutral-300">{s.goal}</div>
                  <div className="mt-1 font-mono text-xs text-neutral-500">
                    {s.target_url.replace(/^https?:\/\//, '')}
                  </div>
                </figcaption>
              </figure>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
